#!/usr/bin/env python3
"""Generates rules.json (EGDA rule data). Edit here, then re-run; rules.json is the artifact the engine loads."""
import json

initials = ["", "b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "zh", "ch", "sh", "r", "z", "c", "s", "y", "w"]
finals = ["a", "o", "e", "i", "u", "v", "ai", "ei", "ui", "ao", "ou", "iu", "ie", "ve", "er", "an", "en", "in", "un", "vn",
          "ang", "eng", "ing", "ong", "ia", "iao", "ian", "iang", "iong", "ua", "uo", "uai", "uan", "uang", "ue"]
pinyin = sorted({i + f for i in initials for f in finals if len(i + f) >= 2})

rules = {
    "version": "0.4.2",
    "oem_stores": ["com.heytap.market", "com.oppo.market", "com.vivo.appstore", "com.bbk.appstore", "com.xiaomi.market",
                   "com.huawei.appmarket", "com.sec.android.app.samsungapps", "com.hihonor.appmarket"],
    "system_installers": ["com.google.android.packageinstaller", "com.android.packageinstaller", "com.miui.packageinstaller",
                          "com.coloros.filemanager", "com.android.chrome", "com.heytap.browser", "com.vivo.browser",
                          "jp.naver.line.android", "com.whatsapp", "com.tencent.mm", "org.telegram.messenger"],
    "perm_ctrl": ["android.permission.BIND_ACCESSIBILITY_SERVICE", "android.permission.BIND_DEVICE_ADMIN",
                  "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE", "android.permission.REQUEST_INSTALL_PACKAGES",
                  "android.permission.READ_SMS", "android.permission.RECEIVE_SMS", "android.permission.SEND_SMS",
                  "android.permission.BIND_VPN_SERVICE", "android.permission.SYSTEM_ALERT_WINDOW"],
    "v3_ctrl": ["BIND_ACCESSIBILITY_SERVICE", "BIND_DEVICE_ADMIN", "READ_SMS", "RECEIVE_SMS", "SEND_SMS", "REQUEST_INSTALL_PACKAGES"],
    "perm_snoop": ["android.permission.PACKAGE_USAGE_STATS", "android.permission.MANAGE_EXTERNAL_STORAGE",
                   "android.permission.QUERY_ALL_PACKAGES", "android.permission.READ_CALL_LOG", "android.permission.READ_CONTACTS"],
    "ad_sdks": {
        "AdMob": ["Lcom/google/android/gms/ads/", "Lcom/google/android/libraries/ads/mobile/sdk/"], "AppLovin": ["Lcom/applovin/"], "UnityAds": ["Lcom/unity3d/ads/", "Lcom/unity3d/services/ads/"],
        "ironSource": ["Lcom/ironsource/"], "Liftoff": ["Lcom/vungle/"], "Mintegral": ["Lcom/mbridge/msdk/"],
        "Pangle": ["Lcom/bytedance/sdk/openadsdk/", "Lcom/bytedance/sdk/pangle/"], "InMobi": ["Lcom/inmobi/"], "Chartboost": ["Lcom/chartboost/"],
        "DTExchange": ["Lcom/fyber/", "Lcom/digitalturbine/"], "MetaAN": ["Lcom/facebook/ads/"], "Moloco": ["Lcom/moloco/"],
        "Bigo": ["Lsg/bigo/ads/"], "Yandex": ["Lcom/yandex/mobile/ads/"], "PubMatic": ["Lcom/pubmatic/"],
        "AmazonAds": ["Lcom/amazon/device/ads/"], "Smaato": ["Lcom/smaato/"], "TradPlus": ["Lcom/tradplus/", "Lcom/tp/adx/"],
        "TopOn": ["Lcom/anythink/"], "GDT": ["Lcom/qq/e/ads/"], "Kuaishou": ["Lcom/kwad/sdk/"], "BaiduAds": ["Lcom/baidu/mobads/", "Lcc/admaster/android/proxy/"],
        "Sigmob": ["Lcom/sigmob/"], "JDAds": ["Lcom/jd/ad/"], "HuaweiAds": ["Lcom/huawei/hms/ads/"], "MiAds": ["Lcom/miui/zeus/"],
        "OppoAds": ["Lcom/heytap/msp/mobad/"], "VivoAds": ["Lcom/vivo/mobilead/"],
    },
    "mediation": ["TradPlus", "TopOn"],
    "sdk_component_prefixes": ["com.applovin", "com.bytedance", "com.mbridge", "com.vungle", "com.google.android.gms",
                               "com.facebook.ads", "com.unity3d", "com.ironsource", "com.inmobi", "sg.bigo", "com.moloco",
                               "com.fyber", "com.chartboost", "com.yandex", "com.tradplus", "com.anythink", "com.kwad",
                               "com.qq.e", "com.baidu.mobads", "com.pubmatic", "com.smaato", "com.amazon.device.ads",
                               "com.google.firebase", "androidx.", "com.google.android.play", "cc.admaster", "com.tp.adx"],
    "lib_component_prefixes": ["com.google.", "com.facebook.", "com.blankj.", "com.pairip.", "io.flutter.", "com.tencent.",
                               "com.squareup.", "com.bumptech.", "com.airbnb.", "com.adjust.", "com.appsflyer.", "com.onesignal.",
                               "com.huawei.", "com.xiaomi.", "com.heytap.", "com.vivo.", "com.oplus.", "com.coloros.", "com.samsung.",
                               "com.android.", "android.", "kotlin", "org.chromium.", "com.microsoft.", "com.amazon.", "com.linecorp.",
                               "io.branch.", "com.braze.", "com.thinkup.", "com.onetrust.", "com.oath.", "com.lxj.", "com.umeng.", "com.hjq.", "com.mixpanel.", "io.sentry.", "com.instabug.", "com.revenuecat.", "com.stripe."],
    "trigger_actions": ["android.intent.action.USER_PRESENT", "android.intent.action.SCREEN_ON", "android.intent.action.SCREEN_OFF",
                        "android.intent.action.ACTION_POWER_CONNECTED", "android.intent.action.ACTION_POWER_DISCONNECTED",
                        "android.intent.action.BATTERY_LOW", "android.intent.action.BATTERY_OKAY",
                        "android.intent.action.BOOT_COMPLETED", "android.intent.action.PACKAGE_ADDED"],
    "ooa_name_regex": r"PopupAd|OutApp|OutSide|LockScreen|Charg(?:e|ing)Screen|Unlock|ScreenOn|Float(?:ing)?Window",
    "obfuscation": {
        "ratio": 0.3,
        "suffixes": ["Activity", "Service", "Receiver", "Provider", "Fragment", "Worker", "Impl"],
        "extra_words": ["app", "apps", "sdk", "api", "ui", "util", "utils", "impl", "mgr", "btn", "img", "msg", "notif", "splash",
                        "onboarding", "premium", "vip", "pdf", "docx", "ocr", "wifi", "qrcode", "barcode", "firebase", "admob",
                        "webview", "deeplink", "fcm", "workmanager", "hms", "oppo", "vivo", "xiaomi", "huawei", "google", "tiktok",
                        "facebook", "instagram", "whatsapp", "wechat", "alipay", "paypal", "login", "logout", "signup", "config",
                        "init", "info", "detail", "details", "setting", "settings", "guide", "home", "main", "launcher", "picker",
                        "viewer", "scanner", "cleaner", "booster", "recovery", "junk", "album", "gallery", "vault", "locker",
                        "bookmark", "shortcut", "widget", "toolbar", "navi", "nav", "fullscreen", "popup", "dialog", "overlay",
                        "async", "sync", "auth", "oauth", "sticker", "stickers", "emoji", "theme", "themes", "botanic", "miffy",
                        "webrtc", "voip", "chathead", "reels", "feed", "inapp", "iap", "sso", "otp", "kyc", "ekyc", "nfc", "bluetooth",
                        "mediastore", "exoplayer", "mraid", "vast", "gdpr", "ccpa", "tcf", "qibla", "xpermission", "umonitor", "playback", "cast", "chromecast", "pip", "multiwindow", "deeplinks", "applink"],
        "pinyin": pinyin,
    },
    "packers": {"dex": ["Lcom/qihoo/util/", "Lcom/stub/StubApp", "Lcom/secneo/", "Lcom/tencent/StubShell/", "Lcom/bangcle/",
                        "Lcom/shell/SuperApplication", "Lcom/baidu/protect/"],
                "libs": ["libjiagu", "libshell", "libsecexe", "libDexHelper", "libexec.so", "libSecShell", "libbaiduprotect"]},
    "bait_categories": {
        "cleaner": ["清理", "垃圾清", "加速", "clean", "cleaner", "booster", "junk", "cache"],
        "antivirus": ["防毒", "病毒", "殺毒", "antivirus", "anti virus", "virus", "security scan"],
        "battery": ["省電", "電池", "电池", "battery saver", "battery"],
        "recovery": ["救援", "恢復", "恢复", "復原", "recover", "recovery", "restore", "undelete"],
        "document": ["pdf", "文件", "文檔", "文档", "閱讀器", "阅读器", "document", "docx", "word office", "office reader", "doc reader"],
        "qr": ["qr", "掃描", "扫描", "條碼", "条码", "scanner", "barcode"],
        "flashlight": ["手電筒", "手电筒", "flashlight", "torch"],
        "vpn": ["vpn"],
        "wifi_tool": ["wifi"],
        "navigation": ["gps", "compass", "route finder", "route planner", "指南針", "指南针", "導航", "导航"],
        "vault": ["vault", "locker", "photo vault", "相片保險箱", "私密相簿", "隐私相册"],
    },
    "bait_names": {"cleaner": "清理、加速", "antivirus": "防毒", "battery": "省電", "recovery": "救回檔案", "document": "看文件",
                   "qr": "掃 QR 碼", "flashlight": "手電筒", "vpn": "VPN", "wifi_tool": "Wi-Fi 工具",
                   "navigation": "GPS、指南針", "vault": "相簿保險箱"},
    "fin_groups": {
        "G1_deposit": ["儲值", "充值", "入金", "deposit", "recharge", "top up", "buy usdt"],
        "G2_withdraw": ["提領", "提現", "提现", "出金", "withdraw", "withdrawal", "withdrawal address"],
        "G3_bonus": ["首儲", "首充", "保證獲利", "保证收益", "穩賺", "first deposit bonus", "guaranteed profit", "daily profit"],
        "G4_staking": ["質押", "质押", "礦池", "矿池", "staking", "mining pool", "liquidity mining"],
        "G5_referral": ["邀請碼", "邀请码", "返傭", "返佣", "invitation code", "referral commission", "indirect referral"],
        "G6_freeze": ["凍結資金", "冻结资金", "解凍", "解冻", "freeze funds", "unfreeze", "margin call"],
        "G7_crypto": ["usdt", "trc20", "erc20", "wallet address", "錢包地址", "钱包地址"],
    },
    "im_sdks": ["Lcom/tencent/imsdk/", "Lio/rong/", "Lcom/netease/nimlib/", "Lcom/hyphenate/", "Lio/openim/"],
    "im_chat_words": ["群組", "群组", "好友", "聊天", "群成員", "群成员", "add friend", "group chat"],
    "im_wallet_words": ["帳戶餘額", "账户余额", "轉帳", "转账", "提領帳戶", "提现账户", "紅包", "红包"],
    "im_secret_words": ["閱後即焚", "阅后即焚", "已讀訊息自動銷毀", "聊天密碼", "聊天密码", "burn after reading"],
    "weekly_words": ["per week", "weekly", "每週", "每周", "/week", "3-day free trial", "free trial"],
    "ai_words": ["ai", "chat", "gpt", "assistant", "nova"],
    "game_engines": {"dex": ["Lcom/unity3d/player/", "Lorg/cocos2dx/", "Lorg/godotengine/", "Lcom/epicgames/"],
                     "libs": ["libunity.so", "libcocos2dcpp.so", "libcocos2djs.so", "libgodot_android.so", "libUE4.so", "libil2cpp.so"]},
    "protected_brands": {},  # filled from genuine APKs by build_brands.py (name list + genuine cert digests)
    "thresholds": {"v1_min_groups": 3, "caution_score": 7, "notice_score": 4, "notice_ad_networks": 4,
                   "nonsense_tokens_per_component": 2},
    "v1_required_any": ["G4_staking", "G7_crypto"],
    "reason_text": {
        "V1": "它有儲值、提領、虛擬貨幣投資的功能，這是投資詐騙常用的手法",
        "V2": "它是可以轉帳的私密聊天 App，詐騙集團常用它帶人進投資群組",
        "V3": "它不是從官方商店來的，還要求可以操控手機的權限",
        "V4": "它的名字很像「{brand}」，但不是{brand}官方的 App",
        "A1": "裡面有 {n} 家廣告公司的程式",
        "A2": "它會在其他畫面上跳出廣告",
        "A3": "它會在您打開手機時自己跑出來",
        "A4": "它刻意把自己的程式藏起來",
        "A5": "{cat}這類 App 常被拿來騙人",
        "A6": "它要求的權限跟它的功能對不上",
        "A8": "它不是從官方商店下載的",
        "A9": "它的程式被加密包起來，看不到裡面在做什麼",
        "A10": "它可能會用每週訂閱的方式收費",
    },
}
json.dump(rules, open("rules.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("rules.json written:", len(pinyin), "pinyin syllables,", len(rules["ad_sdks"]), "ad networks")
